# Compiler binary:
CPP = g++

# Recommended compiler flags for speed:
#	OpenMP enabled
#	full binary code optimization
#	full error and warning reports
#	no range checking within BRKGA:
CFLAGS = -O3 -fopenmp -Wextra -Wall -Weffc++ -ansi -pedantic -Woverloaded-virtual -Wcast-align -Wpointer-arith

# Compiler flags for debugging; uncomment if needed:
#	range checking enabled in the BRKGA API
#	OpenMP disabled
#	no binary code optimization
#CFLAGS = -DRANGECHECK -Wextra -Wall -Weffc++ -ansi -pedantic -Woverloaded-virtual -Wcast-align -Wpointer-arith

# Objects:
OBJECTS = Population.o SimpleSchedulerDecoder.o SimpleSchedulerBRKGA.o

# Targets:
all: SimpleSchedulerBRKGA

SimpleSchedulerBRKGA: $(OBJECTS)
	$(CPP) $(CFLAGS) $(OBJECTS) -o SimpleSchedulerBRKGA

SimpleSchedulerBRKGA.o:
	$(CPP) $(CFLAGS) -c SimpleSchedulerBRKGA.cpp

SimpleSchedulerDecoder.o:
	$(CPP) $(CFLAGS) -c SimpleSchedulerDecoder.cpp

Population.o:
	$(CPP) $(CFLAGS) -c brkgaAPI/Population.cpp

clean:
	rm -f SimpleSchedulerBRKGA $(OBJECTS)
